return {
	flavour = "frappe",
	integrations = {
		cmp = true,
		gitsigns = true,
		nvimtree = true,
		telescope = true,
		mini = true,
		-- For more plugins integrations please scroll down (https://github.com/catppuccin/nvim#integrations)
	},
	custom_highlights = function(colors)
		return {
			SpecsHL = { bg = colors.text },
			MiniTablineFill = { bg = colors.crust },
			MiniTablineCurrent = { fg = colors.text, bg = colors.mantle, style = {} },
			MiniTablineModifiedCurrent = { fg = colors.mauve, bg = colors.mantle },
			MiniTablineModifiedHidden = { fg = colors.mauve, bg = colors.surface0 },
			MiniTablineVisible = { fg = colors.overlay0, bg = colors.surface0 },
			MiniTablineHidden = { fg = colors.overlay0, bg = colors.surface0 },
			-- MatchParen = { bg = colors.surface1 },
			markdownTSTitle = { bold = true, fg = colors.green },
			TSPunctSpecial = { bold = true, fg = colors.green },
			-- QuickFixLine = { bg = colors.mantle },
			IndentBlanklineChar = { fg = colors.surface2 },
			IndentBlanklineContextChar = { fg = colors.mauve },
			StatusLineGitAdd = { fg = colors.green, bg = colors.mantle },
			StatusLineGitRemoved = { fg = colors.red, bg = colors.mantle },
			StatusLineGitChanged = { fg = colors.yellow, bg = colors.mantle },
			StatusLineGitBranch = { fg = colors.surface2, bg = colors.mantle },
			StatusLineLocation = { fg = colors.sapphire, bg = colors.surface1 },
			StatusLinePosition = { fg = colors.green, bg = colors.surface1 },
			StatusLine = { bg = colors.mantle, fg = colors.fg },
			StatusLineFile = { fg = colors.text, bg = colors.base },
			StatusLineFileSep = { bg = colors.mantle, fg = colors.base },
			StatusLinePositionIcon = { fg = colors.mantle, bg = colors.green },
			StatusLinePositionIconSep = { bg = colors.surface1, fg = colors.green },
			StatusLineLocationSep = { fg = colors.surface1, bg = colors.mantle },
			StatusLineError = { fg = colors.red },
			StatusLineInfo = { fg = colors.green },
			StatusLineHint = { fg = colors.mauve },
			StatusLineWarn = { fg = colors.yellow },
			MainSep = { fg = colors.sapphire, bg = colors.base, style = { "bold" } },
			Main = { bg = colors.sapphire, fg = colors.base, style = { "bold" } },
			ModeCSep = { fg = colors.green, bg = colors.base, style = { "bold" } },
			ModeC = { bg = colors.green, fg = colors.base, style = { "bold" } },
			ModeISep = { fg = colors.mauve, bg = colors.base, style = { "bold" } },
			ModeI = { bg = colors.mauve, fg = colors.base, style = { "bold" } },
			ModeTSep = { fg = colors.green, bg = colors.base, style = { "bold" } },
			ModeT = { bg = colors.green, fg = colors.base, style = { "bold" } },
			ModeNSep = { fg = colors.red, bg = colors.base, style = { "bold" } },
			ModeN = { bg = colors.red, fg = colors.base, style = { "bold" } },
			ModeVSep = { fg = colors.sapphire, bg = colors.base, style = { "bold" } },
			ModeV = { bg = colors.sapphire, fg = colors.base, style = { "bold" } },
			ModeRSep = { fg = colors.peach, bg = colors.base, style = { "bold" } },
			ModeR = { bg = colors.peach, fg = colors.base, style = { "bold" } },
			TelescopePromptPrefix = { bg = colors.crust },
			TelescopePromptNormal = { bg = colors.crust },
			TelescopeResultsNormal = { bg = colors.mantle },
			TelescopePreviewNormal = { bg = colors.crust },
			TelescopePromptBorder = { bg = colors.crust, fg = colors.crust },
			TelescopeResultsBorder = { bg = colors.mantle, fg = colors.crust },
			TelescopePreviewBorder = { bg = colors.crust, fg = colors.crust },
			TelescopePromptTitle = { fg = colors.crust, bg = colors.green },
			TelescopeResultsTitle = { fg = colors.text, bg = colors.red },
			TelescopePreviewTitle = { fg = colors.crust, bg = colors.sapphire },
		}
	end,
}
